### ISSUE TITLE
[discuss] core api naming

### ISSUE THREAD

**Issue by lburgazzoli** [coreos/jetcd#146]
Hi,

the current Client interface is in fact a facade to create clients for etcd functionalities so I'm wondering if it could make sense to:

- rename Client to Etcd or JEtcd
- add ``Client`` suffix to the client so we match the getter names ``get*Client``

Something like:

```java
Etcd etcd = Etcd.builder().build();
KVClient kvClient = etcd.getKVClient();
```
A similar naming can be found in [Orbitz's consul client](https://github.com/OrbitzWorldwide/consul-client)

**Comment by fanminshi** [comment]
`rename Client to Etcd or JEtcd`
I don't we need to have `etcd` keyword in any of the interface. Since it is quite obvious that you are using a java client for etcd. I don't user will gain additional clarity from the `etcd` keyword.

`add Client suffix to the client so we match the getter names get*Client`
I would like jetcd api naming to match that of the go client. In go client, there aren't any `client` suffix. In this way, the user from go to java or vice versa should have a consistent experience. 
Also `getKVClient()` already tell the user the return object will be a client. I am not sure if `Client` in `KVClient`buys additional clarity for user.
