### ISSUE TITLE
whatcher.listen() should give an error when etcd servers are down.

### ISSUE THREAD

**Issue by akd31** [coreos/jetcd#224]
Hello,

I tried to test watchers.listen() when etcd servers are down. It keeps locked and when etcd servers up again and make some change on the key listened it works and get the change. I think it should aware the servers status and give an error, shouldn't it ?

**Comment by heyitsanthony** [comment]
The go client's watch hides connection errors so that reconnection appears seamless. There are cases without watches where it's useful to detect disconnects, so baking transport error information into watches is less flexible than what would be needed in general. Do you have a specific use case in mind?

**Comment by akd31** [comment]
Actually I am building my own client based on yours and just tried this scenario.I don't think this is a big issue and there is no problematic use case in my mind.

**Comment by fanminshi** [comment]
@akd31 I am interested on what kind of client are you building base on the jetcd

**Comment by akd31** [comment]
It is sufficient. I just make some arrangements and puts some limits on my users.

**Comment by fanminshi** [comment]
Cool! also suggestions to improve jetcd are welcomed if you seen any.

**Comment by fanminshi** [comment]
closing.
